# 数据库连接配置
databaseinfo:
  driverClass: com.mysql.cj.jdbc.Driver
  connectionURL: jdbc:mysql://192.168.0.238:3306/ibn_rms?useUnicode=true&characterEncoding=UTF-8&useSSL=false
  userId: root
  password: 123456
sysconfig:
  basepackage: com.ibn.rms
  # 根据哪些表生成代码
  generatetable:
    - ibn_rms.user_base

velocityconfig:
  # velocity模板路径
  basepath: /templates/ibn
  # 哪些模板需要生成
  template:
    service:
      # 模板名称
      name: Service.java.vm
      # 项目名称
      module: crm-domain
      # 基础包名下的子包名
      outPutPackage: service
    serviceImpl:
      name: ServiceImpl.java.vm
      module: crm
      outPutPackage: service.impl
    test:
      name: ServiceImplTest.java.vm
      module: crm
      type: test
      outPutPackage: "#{sysconfig.basepackage}.service.impl"
    mapper:
      name: Dao.xml.vm
      module: crm
      type: mapper
      outPutPackage: mybatis
    dao:
      name: Dao.java.vm
      module: crm
      outPutPackage: dao
    do:
      name: DO.java.vm
      module: crm-domain
      outPutPackage: entity
    dto:
      name: DTO.java.vm
      module: crm-domain
      outPutPackage: domain
    vo:
      name: VO.java.vm
      module: crm-mgt
      outPutPackage: vo
    ao:
      name: AO.java.vm
      module: crm-mgt
      outPutPackage: ao
    aoImpl:
      name: AOImpl.java.vm
      module: crm-mgt
      outPutPackage: ao.impl
    controller:
      name: Controller.java.vm
      module: crm-mgt
      outPutPackage: controller
userconfig:
  # 用户自定义配置
  configMap:
    author: RenBin
    curTime: 2020/8/11 21:45
    projectName: ibn-rms


