spring:
# 数据库连接配置
databaseinfo:
  driverClass: com.mysql.cj.jdbc.Driver
  connectionURL: jdbc:mysql://192.167.12.238:3306/springbootplus?useUnicode=true&characterEncoding=UTF-8&useSSL=false
  userId: root
  password: 123456
sysconfig:
  basepackage: com.mysteel.oilchem.crm
  # 根据哪些表生成代码
  generatetable:
    - user_base
velocityconfig:
  # velocity模板路径
  basepath: /templates
  # 哪些模板需要生成
  template: {
    service: service.java.vm
  }

userconfig:
  # 用户自定义配置
  configMap: {
    author: RenBin
  }



